# Generated by Django 5.1.1 on 2024-10-01 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Game Title")),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Platform Title"),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Release Date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform",
                "verbose_name_plural": "Platforms",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="GameVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=300, verbose_name="Version")),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                (
                    "is_played",
                    models.BooleanField(default=False, verbose_name="Played"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Release Date"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tracker.game"
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Version",
                "verbose_name_plural": "Game Versions",
                "ordering": ["game"],
            },
        ),
        migrations.AddField(
            model_name="game",
            name="platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.platform",
            ),
        ),
        migrations.CreateModel(
            name="PlatformVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=300, verbose_name="Version")),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Release Date"
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tracker.platform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Version",
                "verbose_name_plural": "Platform Versions",
                "ordering": ["platform"],
            },
        ),
    ]
