# Generated by Django 5.1.1 on 2024-10-08 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Game Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Release Date"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="IGDB Link"
                    ),
                ),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GameEngine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="Game Engine Name"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="IGDB Link"
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Engine",
                "verbose_name_plural": "Game Engines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="Platform Name"),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Release Date"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="IGDB Link"
                    ),
                ),
                (
                    "generation",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Generation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform",
                "verbose_name_plural": "Platforms",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GameVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=300, verbose_name="Version")),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Release Date"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                (
                    "played_status",
                    models.IntegerField(
                        choices=[(0, "Unplayed"), (1, "Played"), (2, "Completed")],
                        default=0,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tracker.game"
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Version",
                "verbose_name_plural": "Game Versions",
                "ordering": ["game"],
            },
        ),
        migrations.AddField(
            model_name="game",
            name="platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tracker.platform",
            ),
        ),
        migrations.CreateModel(
            name="PlatformVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=300, verbose_name="Version")),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Release Date"
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tracker.platform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Version",
                "verbose_name_plural": "Platform Versions",
                "ordering": ["platform"],
            },
        ),
    ]
